CREATE TABLE IF NOT EXISTS metrics (
    id                       VARCHAR PRIMARY KEY,
    name                     VARCHAR NOT NULL,
    description              VARCHAR,
    unit                     VARCHAR,
    metric_type              INTEGER NOT NULL,
    aggregation_temporality  INTEGER,
    is_monotonic             BOOLEAN,
    metadata                 JSON,
    service_name             VARCHAR,
    resource_attributes      JSON,
    resource_dropped_attributes_count UBIGINT NOT NULL,
    resource_schema_url      VARCHAR,
    scope_name               VARCHAR,
    scope_version            VARCHAR,
    scope_attributes         JSON,
    scope_dropped_attributes_count UBIGINT NOT NULL,
    scope_schema_url         VARCHAR,
    attributes               JSON,
    start_time_ns            UBIGINT,
    time_ns                  UBIGINT NOT NULL,
    value_double             DOUBLE,
    int_value                BIGINT,
    count                    UBIGINT,
    sum                      DOUBLE,
    min                      DOUBLE,
    max                      DOUBLE,
    exemplars                JSON,
    flags                    UBIGINT NOT NULL,
    data                     JSON NOT NULL,
    received_at              TIMESTAMP NOT NULL DEFAULT current_timestamp
);

CREATE INDEX IF NOT EXISTS idx_metrics_name_time ON metrics (name, time_ns DESC);
CREATE INDEX IF NOT EXISTS idx_metrics_service ON metrics (service_name);
